coco_de_guide:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "WLFHBRL-SGC69960"
      user: "R88SKEERTHI"
      password: "eyJraWQiOiIxMzA2MDc3MTg0MDUiLCJhbGciOiJFUzI1NiJ9.eyJwIjoiNTEwMTg2MjQ0OjUxMDE4NjI0NCIsImlzcyI6IlNGOjEwNTYiLCJleHAiOjE3ODg1MjA4ODd9.sfx6mCdNaa8ZjUKKtOEJ3cDcq3g7lz1yWoZUgm6Yzcs_vQ8tkMnkiyG15QL_xoD9jhcAiwSktxE7y0uHWeA7Rw"
      role: DEMO_ROLE
      database: DEMO_DB
      warehouse: DEMO_WH
      schema: TPCH_TRANSFORMED
      threads: 4